flutter:
  uses-material-design: true

name: diary
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4
  table_calendar: ^3.0.9  # 달력 UI
  intl: ^0.19.0  # 날짜 포맷팅

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^6.0.0
  test: ^1.25.6
